version: "3.8"

services:
  frontend:
    image: protik111/todo-front-dockerize-ec2:latest
    container_name: todo-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
    restart: always